/*****************************************************************************
* Model: qpc-stm32-m3.qm
* File:  ..//include/qm/qm_events.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${../::include::qm::qm_events.h} .........................................*/
#ifndef __QM_EVENTS_H__
#define __QM_EVENTS_H__

#include "qp_port.h"

typedef struct general_evt_tag {
    QEvt super;
} general_evt;



#endif
