/*****************************************************************************
* Model: qpc-stm32-m3.qm
* File:  ..//src/qm/qm_leds.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${../::src::qm::qm_leds.c} ...............................................*/
#include "qm/qm_leds.h"


/*${Node::qm_leds} .........................................................*/
typedef struct {
/* protected: */
    QMActive super;

/* public: */
    QTimeEvt timer;
} qm_leds;

/* protected: */
static QState qm_leds_initial(qm_leds * const me, QEvt const * const e);
static QState qm_leds_active  (qm_leds * const me, QEvt const * const e);
static QState qm_leds_active_e(qm_leds * const me);
static QState qm_leds_active_i(qm_leds * const me);
static QMState const qm_leds_active_s = {
    (QMState const *)0, /* superstate (top) */
    Q_STATE_CAST(&qm_leds_active),
    Q_ACTION_CAST(&qm_leds_active_e),
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(&qm_leds_active_i)
};
static QState qm_leds_on  (qm_leds * const me, QEvt const * const e);
static QState qm_leds_on_e(qm_leds * const me);
static QMState const qm_leds_on_s = {
    &qm_leds_active_s, /* superstate */
    Q_STATE_CAST(&qm_leds_on),
    Q_ACTION_CAST(&qm_leds_on_e),
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};
static QState qm_leds_off  (qm_leds * const me, QEvt const * const e);
static QState qm_leds_off_e(qm_leds * const me);
static QMState const qm_leds_off_s = {
    &qm_leds_active_s, /* superstate */
    Q_STATE_CAST(&qm_leds_off),
    Q_ACTION_CAST(&qm_leds_off_e),
    Q_ACTION_CAST(0), /* no exit action */
    Q_ACTION_CAST(0)  /* no intitial tran. */
};



static qm_leds l_qm_leds;

QActive* const ao_qm_leds = (QActive*)&l_qm_leds;

/*${Node::qm_leds_ctor} ....................................................*/
void qm_leds_ctor(void) {
    qm_leds *me = &l_qm_leds;
    QMActive_ctor(&me->super, Q_STATE_CAST(&qm_leds_initial));

    QTimeEvt_ctorX (&me->timer, &me->super, LEDS_IN_TIMEOUT_SIG, 0U);
}
/*${Node::qm_leds} .........................................................*/
/*${Node::qm_leds::SM} .....................................................*/
static QState qm_leds_initial(qm_leds * const me, QEvt const * const e) {
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { /* transition-action table */
        &qm_leds_active_s, /* target state */
        {
            Q_ACTION_CAST(&qm_leds_active_e), /* entry */
            Q_ACTION_CAST(&qm_leds_active_i), /* init.tran. */
            Q_ACTION_CAST(0) /* zero terminator */
        }
    };
    /* ${Node::qm_leds::SM::initial} */

    LOG("leds init");
    return QM_TRAN_INIT(&tatbl_);
}
/*${Node::qm_leds::SM::active} .............................................*/
/* ${Node::qm_leds::SM::active} */
static QState qm_leds_active_e(qm_leds * const me) {
    QTimeEvt_armX(&me->timer,  QF_TICKS_PER_SEC, QF_TICKS_PER_SEC);
    return QM_ENTRY(&qm_leds_active_s);
}
/* ${Node::qm_leds::SM::active::initial} */
static QState qm_leds_active_i(qm_leds * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* transition-action table */
        &qm_leds_on_s, /* target state */
        {
            Q_ACTION_CAST(&qm_leds_on_e), /* entry */
            Q_ACTION_CAST(0) /* zero terminator */
        }
    };
    /* ${Node::qm_leds::SM::active::initial} */
    return QM_TRAN_INIT(&tatbl_);
}
/* ${Node::qm_leds::SM::active} */
static QState qm_leds_active(qm_leds * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* avoid compiler warning in case 'me' is not used */
    return status_;
}
/*${Node::qm_leds::SM::active::on} .........................................*/
/* ${Node::qm_leds::SM::active::on} */
static QState qm_leds_on_e(qm_leds * const me) {
    bsp_led_on();
    LOG("led on");
    (void)me; /* avoid compiler warning in case 'me' is not used */
    return QM_ENTRY(&qm_leds_on_s);
}
/* ${Node::qm_leds::SM::active::on} */
static QState qm_leds_on(qm_leds * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${Node::qm_leds::SM::active::on::LEDS_IN_TIMEOUT} */
        case LEDS_IN_TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* transition-action table */
                &qm_leds_off_s, /* target state */
                {
                    Q_ACTION_CAST(&qm_leds_off_e), /* entry */
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*${Node::qm_leds::SM::active::off} ........................................*/
/* ${Node::qm_leds::SM::active::off} */
static QState qm_leds_off_e(qm_leds * const me) {
    bsp_led_off();
    LOG("led off");
    (void)me; /* avoid compiler warning in case 'me' is not used */
    return QM_ENTRY(&qm_leds_off_s);
}
/* ${Node::qm_leds::SM::active::off} */
static QState qm_leds_off(qm_leds * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${Node::qm_leds::SM::active::off::LEDS_IN_TIMEOUT} */
        case LEDS_IN_TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* transition-action table */
                &qm_leds_on_s, /* target state */
                {
                    Q_ACTION_CAST(&qm_leds_on_e), /* entry */
                    Q_ACTION_CAST(0) /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

